// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prontto.Infrastructure.Persistence.Context;

#nullable disable

namespace Prontto.Infrastructure.Migrations
{
    [DbContext(typeof(ContextoBancoDados))]
    [Migration("20260604190548_RF04_ServicosDisputas")]
    partial class RF04_ServicosDisputas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prontto.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .HasColumnType("text")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("endereco_ip");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.HasIndex("UsuarioId", "CriadoEm");

                    b.ToTable("logs_auditoria", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_exibicao");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.CategoriaUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.HasKey("UsuarioId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("usuarios_categorias", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("cidades", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.CidadeUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.HasKey("UsuarioId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("usuarios_cidades", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Cobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("LiberadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("liberado_em");

                    b.Property<DateTime?>("PagadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pago_em");

                    b.Property<string>("PagarmeOrderId")
                        .HasColumnType("text")
                        .HasColumnName("pagarme_order_id");

                    b.Property<string>("PagarmePagamentoId")
                        .HasColumnType("text")
                        .HasColumnName("pagarme_payment_id");

                    b.Property<string>("PixCopiaCola")
                        .HasColumnType("text")
                        .HasColumnName("pix_copia_cola");

                    b.Property<DateTime?>("PixExpiracaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pix_expira_em");

                    b.Property<string>("PixQrCode")
                        .HasColumnType("text")
                        .HasColumnName("pix_qr_code");

                    b.Property<DateTime?>("RetidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retido_em");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaAdmin")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("taxa_admin");

                    b.Property<decimal>("ValorPrestador")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_prestador");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("PagarmeOrderId")
                        .IsUnique()
                        .HasFilter("pagarme_order_id IS NOT NULL");

                    b.HasIndex("ServicoId")
                        .IsUnique();

                    b.HasIndex("Status", "PixExpiracaoEm");

                    b.ToTable("cobrancas", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.DadosBancarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agencia")
                        .HasColumnType("text")
                        .HasColumnName("agencia");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chave_pix");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeBanco")
                        .HasColumnType("text")
                        .HasColumnName("nome_banco");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("text")
                        .HasColumnName("numero_conta");

                    b.Property<string>("TipoChavePix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_chave_pix");

                    b.Property<string>("TipoConta")
                        .HasColumnType("text")
                        .HasColumnName("tipo_conta");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("dados_bancarios", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Disputa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AbertaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aberto_por_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DecisaoAdmin")
                        .HasColumnType("text")
                        .HasColumnName("decisao_admin");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("ResolvidaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolvido_por_id");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AbertaPorId");

                    b.HasIndex("ResolvidaPorId");

                    b.HasIndex("ServicoId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("disputas", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.ImagemPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("Aprovada")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloudinary_public_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("Moderada")
                        .HasColumnType("boolean")
                        .HasColumnName("moderado");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_exibicao");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Ordem")
                        .HasFilter("deletado_em IS NULL AND aprovado = TRUE");

                    b.ToTable("imagens_portfolio", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.MensagemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool?>("ImagemAprovada")
                        .HasColumnType("boolean")
                        .HasColumnName("imagem_aprovada");

                    b.Property<bool>("ImagemModerada")
                        .HasColumnType("boolean")
                        .HasColumnName("imagem_moderada");

                    b.Property<string>("PapelRemetente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel_remetente");

                    b.Property<Guid?>("RemetenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("remetente_id");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<string>("StatusProposta")
                        .HasColumnType("text")
                        .HasColumnName("status_proposta");

                    b.Property<string>("TipoMensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_mensagem");

                    b.Property<decimal?>("ValorProposta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_proposta");

                    b.HasKey("Id");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("ServicoId", "CriadoEm");

                    b.ToTable("mensagens_servico", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean")
                        .HasColumnName("lido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("ReferenciaId")
                        .HasColumnType("text")
                        .HasColumnName("referencia_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Lida", "CriadoEm");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiracaoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("endereco_ip");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<string>("SubstituidoPor")
                        .HasColumnType("text")
                        .HasColumnName("substituido_por");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId", "RevogadoEm");

                    b.ToTable("tokens_renovacao", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AgendadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agendado_em");

                    b.Property<DateTime?>("AguardandoConfirmacaoDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aguardando_confirmacao_desde");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<Guid?>("PrestadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("prestador_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TaxaAdminRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("taxa_admin_percentual");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("AguardandoConfirmacaoDesde");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("Status");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("CidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("cidade_id");

                    b.Property<string>("Cpf")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Especialidade")
                        .HasColumnType("text")
                        .HasColumnName("especialidade");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("url_foto_perfil");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_senha");

                    b.Property<decimal>("MediaAvaliacoes")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("media_avaliacoes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_conta");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("integer")
                        .HasColumnName("total_avaliacoes");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("slug IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Prontto.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.CategoriaUsuario", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Usuarios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.CidadeUsuario", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Usuarios")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Cidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Servico", "Servico")
                        .WithOne("Cobranca")
                        .HasForeignKey("Prontto.Domain.Entities.Cobranca", "ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.DadosBancarios", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithOne("DadosBancarios")
                        .HasForeignKey("Prontto.Domain.Entities.DadosBancarios", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Disputa", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "AbertaPor")
                        .WithMany()
                        .HasForeignKey("AbertaPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontto.Domain.Entities.Usuario", "ResolvidaPor")
                        .WithMany()
                        .HasForeignKey("ResolvidaPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prontto.Domain.Entities.Servico", "Servico")
                        .WithOne("Disputa")
                        .HasForeignKey("Prontto.Domain.Entities.Disputa", "ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbertaPor");

                    b.Navigation("ResolvidaPor");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.ImagemPortfolio", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ImagensPortfolio")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.MensagemServico", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Remetente")
                        .WithMany("Mensagens")
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prontto.Domain.Entities.Servico", "Servico")
                        .WithMany("Mensagens")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Remetente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Servico", b =>
                {
                    b.HasOne("Prontto.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prontto.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prontto.Domain.Entities.Usuario", "Cliente")
                        .WithMany("ServicosComoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Prontto.Domain.Entities.Usuario", "Prestador")
                        .WithMany("ServicosComoPrestador")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Cidade");

                    b.Navigation("Cliente");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Servico", b =>
                {
                    b.Navigation("Cobranca");

                    b.Navigation("Disputa");

                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("Prontto.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Cidades");

                    b.Navigation("DadosBancarios");

                    b.Navigation("ImagensPortfolio");

                    b.Navigation("Mensagens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ServicosComoCliente");

                    b.Navigation("ServicosComoPrestador");
                });
#pragma warning restore 612, 618
        }
    }
}
